# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rack-gist}
  s.version = "1.1.9"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Daniel Huckstep"]
  s.date = %q{2011-10-30}
  s.description = %q{Load gists in the background. KTHXBYE!}
  s.email = %q{darkhelmet@darkhelmetlive.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rvmrc",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/rack/gist.rb",
    "rack-gist.gemspec",
    "spec/body-full.html",
    "spec/body-multiple.html",
    "spec/body-none.html",
    "spec/body-partial.html",
    "spec/body-private.html",
    "spec/full-gist.js",
    "spec/partial-gist.js",
    "spec/rack-gist_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/darkhelmet/rack-gist}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Asynchronous Github Gists. All with rack.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<nokogiri>, ["~> 1.4"])
      s.add_runtime_dependency(%q<rest-client>, ["~> 1.6"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6"])
      s.add_development_dependency(%q<fakeweb>, ["~> 1.2.8"])
      s.add_development_dependency(%q<rspec>, ["~> 1.3.0"])
      s.add_development_dependency(%q<yard>, ["~> 0.5.8"])
      s.add_development_dependency(%q<rack>, ["~> 1.2.1"])
      s.add_development_dependency(%q<activesupport>, ["~> 2.3.8"])
    else
      s.add_dependency(%q<nokogiri>, ["~> 1.4"])
      s.add_dependency(%q<rest-client>, ["~> 1.6"])
      s.add_dependency(%q<jeweler>, ["~> 1.6"])
      s.add_dependency(%q<fakeweb>, ["~> 1.2.8"])
      s.add_dependency(%q<rspec>, ["~> 1.3.0"])
      s.add_dependency(%q<yard>, ["~> 0.5.8"])
      s.add_dependency(%q<rack>, ["~> 1.2.1"])
      s.add_dependency(%q<activesupport>, ["~> 2.3.8"])
    end
  else
    s.add_dependency(%q<nokogiri>, ["~> 1.4"])
    s.add_dependency(%q<rest-client>, ["~> 1.6"])
    s.add_dependency(%q<jeweler>, ["~> 1.6"])
    s.add_dependency(%q<fakeweb>, ["~> 1.2.8"])
    s.add_dependency(%q<rspec>, ["~> 1.3.0"])
    s.add_dependency(%q<yard>, ["~> 0.5.8"])
    s.add_dependency(%q<rack>, ["~> 1.2.1"])
    s.add_dependency(%q<activesupport>, ["~> 2.3.8"])
  end
end

